package Frame;

import javax.swing.JOptionPane;
import Frame.Choice;
import java.awt.event.WindowEvent;

public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Image_background_2 = new javax.swing.JLabel();
        Icon_exit = new javax.swing.JLabel();
        Icon_minimize = new javax.swing.JLabel();
        Username_field = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password_field = new javax.swing.JPasswordField();
        LOGIN = new javax.swing.JLabel();
        Button_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setMaximumSize(new java.awt.Dimension(1180, 690));
        setMinimumSize(new java.awt.Dimension(1180, 690));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1180, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 26, 26));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Image_background_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/image.JPG"))); // NOI18N
        jPanel1.add(Image_background_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 480, 450));

        Icon_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Icon_exit.setForeground(new java.awt.Color(255, 255, 255));
        Icon_exit.setText("X");
        Icon_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Icon_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Icon_exitMouseClicked(evt);
            }
        });
        jPanel1.add(Icon_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 20, 30));

        Icon_minimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Icon_minimize.setForeground(new java.awt.Color(255, 255, 255));
        Icon_minimize.setText("-");
        Icon_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Icon_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Icon_minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(Icon_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 20, 30));

        Username_field.setBackground(new java.awt.Color(16, 16, 16));
        Username_field.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Username_field.setForeground(new java.awt.Color(255, 255, 255));
        Username_field.setBorder(null);
        Username_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Username_fieldMouseClicked(evt);
            }
        });
        jPanel1.add(Username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 270, 40));

        Password.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, 20));

        Username.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 90, 20));

        Password_field.setBackground(new java.awt.Color(16, 16, 16));
        Password_field.setForeground(new java.awt.Color(255, 255, 255));
        Password_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Password_field.setBorder(null);
        Password_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Password_fieldMouseClicked(evt);
            }
        });
        Password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(Password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 270, 40));

        LOGIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        LOGIN.setText("LOGIN");
        jPanel1.add(LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        Button_login.setBackground(new java.awt.Color(79, 54, 105));
        Button_login.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Button_login.setText("Sign in");
        Button_login.setBorder(null);
        Button_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_loginActionPerformed(evt);
            }
        });
        jPanel1.add(Button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 890, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/background_image.JPG"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1180, 690));
        jLabel1.setMinimumSize(new java.awt.Dimension(1180, 690));
        jLabel1.setPreferredSize(new java.awt.Dimension(1180, 690));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_fieldActionPerformed

    private void Icon_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icon_minimizeMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_Icon_minimizeMouseClicked

    private void Icon_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Icon_exitMouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to quit?", "Exit", dialogButton);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_Icon_exitMouseClicked

    private void Username_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_fieldMouseClicked
        Username_field.setText("");
    }//GEN-LAST:event_Username_fieldMouseClicked

    private void Password_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_fieldMouseClicked
        Password_field.setText("");
    }//GEN-LAST:event_Password_fieldMouseClicked

    private void Button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_loginActionPerformed
        String username = Username_field.getText();
        String password = Password_field.getText();
        
        if((username.contains("Kari") && (password.contains("testowe")))) {
            Username_field.setText(null);
            Password_field.setText(null);
            systemExit();
        
            dispose();
            Choice Info = new Choice();
            Info.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(null, "Invalid login details", "Login error", JOptionPane.ERROR_MESSAGE);
            Username_field.setText(null);
            Password_field.setText(null);
        }
    }//GEN-LAST:event_Button_loginActionPerformed

    private void systemExit() {
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSED);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_login;
    private javax.swing.JLabel Icon_exit;
    private javax.swing.JLabel Icon_minimize;
    private javax.swing.JLabel Image_background_2;
    private javax.swing.JLabel LOGIN;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField Password_field;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField Username_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}